# Generated by Django 4.2.3 on 2023-07-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STK_SIZE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SIZE_NAME', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='STK_TYPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE_NAME', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='STK_PRD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRD_NAME', models.CharField(max_length=100)),
                ('PRD_NUMB', models.IntegerField(null=True)),
                ('PRD_PRICE', models.FloatField()),
                ('SIZE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stk_size')),
                ('TYPE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stk_type')),
            ],
            options={
                'unique_together': {('PRD_NAME', 'TYPE_ID', 'SIZE_ID')},
            },
        ),
    ]
